name: CI
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/generate-help-file.yaml
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Convert README to help file
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: codecompanion-spinner
          demojify: true
          shiftheadinglevelby: -1
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update help file"
          branch: docs/update-help-file
          title: "docs: update help file"
